import globals from 'globals';
import IMPORT_PLUGIN from 'eslint-plugin-import';
import PRETTIER_PLUGIN from 'eslint-plugin-prettier';

export default [
  {
    files: ['src/browser/**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      globals: {
        ...globals.browser,
        Cypress: false,
        cy: false
      }
    },
    plugins: {
      prettier: PRETTIER_PLUGIN,
      import: IMPORT_PLUGIN,
    },
    rules: {
      //'prettier/prettier': 'warn',
      eqeqeq: 'error',
      complexity: ['error', 12],
      'max-depth': ['error', 5],
      'max-lines': ['error', { max: 300, skipBlankLines: true }],
      'max-lines-per-function': ['error', 135],
      'max-nested-callbacks': ['error', 5],
      'max-params': ['error', 10],
      'no-alert': 'error',
      'no-await-in-loop': 'error',
      'no-cond-assign': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-const-assign': 'error',
      'no-duplicate-imports': 'error',
      'no-constant-condition': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-else-if': 'error',
      'no-else-return': 'error',
      'no-empty': 'error',
      'no-empty-function': 'error',
      'no-eval': 'error',
      'no-import-assign': 'error',
      'no-invalid-this': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-magic-numbers': ['error', { ignore: [-1, 0, 1, 2, 100] }],
      'no-octal': 'error',
      'no-param-reassign': 'error',
      'no-redeclare': 'error',
      'no-restricted-globals': [
        'error',
        {
          name: 'document',
          message: 'Use window.document instead.',
        },
      ],
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-self-assign': 'error',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': 'error',
      'no-unreachable': 'error',
      'no-undef': 'error',
      'no-unused-vars': ['error', { ignoreRestSiblings: true }],
      'no-use-before-define': 'error',
      'no-useless-catch': 'error',
      'no-var': 'error',
      'no-warning-comments': 'error',
      'no-with': 'error',
      'no-template-curly-in-string': 'error',
      'prefer-const': 'error',
      'require-atomic-updates': 'error',
      'require-unicode-regexp': 'error',
      'import/export': 'error',
      'import/no-unresolved': 'error',
      'import/named': 'error',
      'import/default': 'error',
      'import/no-absolute-path': 'error',
      'import/no-self-import': 'error',
      'import/no-cycle': 'error',
      // it's not okay to import dev dependencies in production code
      'import/no-extraneous-dependencies': ['error', { devDependencies: false }],
      'import/no-mutable-exports': 'error',
      'import/no-unused-modules': 'error',
    },
  },
];
